language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - nightly
  - hhvm
  - hhvm-nightly

matrix:
  include:
    - php: 5.3
      dist: precise
  allow_failures:
    - php: nightly
    - php: hhvm-nightly
  fast-finish: true

notifications:
  irc: "chat.freenode.net#picocms"

before_install:
  - export PATH="$TRAVIS_BUILD_DIR/_build:$PATH"

install:
  - install.sh

before_script:
  - export PATH="$TRAVIS_BUILD_DIR/vendor/bin:$PATH"

script:
  - phpcs --standard=.phpcs.xml "$TRAVIS_BUILD_DIR"

after_success:
  - deploy-phpdoc-branch.sh

before_deploy:
  - deploy-phpdoc-release.sh
  - create-release-archive.sh "$TRAVIS_TAG"

deploy:
  provider: releases
  api_key: ${GITHUB_OAUTH_TOKEN}
  file: pico-release-$TRAVIS_TAG.tar.gz
  skip_cleanup: true
  on:
    tags: true
    php: 5.3

dist: trusty
sudo: false
