language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm
  - nightly

matrix:
  allow_failures:
    - php: nightly
  fast-finish: true

install:
  - composer install

before_script:
  - export PATH="$TRAVIS_BUILD_DIR/_build:$TRAVIS_BUILD_DIR/vendor/bin:$PATH"

script:
  - phpcs --standard=.phpcs.xml "$TRAVIS_BUILD_DIR"

after_success:
  - deploy-phpdoc-branch.sh

before_deploy:
  - deploy-phpdoc-release.sh
  - composer install --no-dev --optimize-autoloader
  - find vendor/ -type d -path 'vendor/*/*/.git' -print0 | xargs -0 rm -rf
  - mv index.php.dist index.php
  - tar -czf "pico-release-$TRAVIS_TAG.tar.gz" README.md LICENSE CONTRIBUTING.md CHANGELOG.md composer.json composer.lock config content-sample lib plugins themes vendor .htaccess index.php

deploy:
  provider: releases
  api_key: ${GITHUB_OAUTH_TOKEN}
  file: pico-release-$TRAVIS_TAG.tar.gz
  skip_cleanup: true
  on:
    tags: true
    php: 5.3

sudo: false
