dist: trusty
sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache/files

jobs:
  include:
    # Test stage
    - php: 5.3
      dist: precise
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: nightly
    - php: hhvm
    - php: hhvm-nightly

    # Deployment stage
    - stage: deploy
      sudo: required
      install:
        - '[ "$TRAVIS_PULL_REQUEST" == "false" ] || travis_terminate 0'
        - '[ -n "$TRAVIS_TAG" ] || [[ ",$DEPLOY_PHPDOC_BRANCHES," == *,"$TRAVIS_BRANCH",* ]] || travis_terminate 0'
        - install.sh --deploy
      script:
        - deploy.sh
      before_deploy:
        - create-release.sh "$TRAVIS_BUILD_DIR/pico-release-$TRAVIS_TAG.tar.gz"
      deploy:
        provider: releases
        api_key: ${GITHUB_OAUTH_TOKEN}
        file: pico-release-$TRAVIS_TAG.tar.gz
        skip_cleanup: true
        draft: true
        on:
          tags: true

  # Ignore nightly build failures
  allow_failures:
    - php: nightly
    - php: hhvm-nightly
  fast-finish: true

before_install:
  - export PATH="$TRAVIS_BUILD_DIR/_build:$PATH"

install:
  - install.sh

before_script:
  - export PATH="$TRAVIS_BUILD_DIR/vendor/bin:$PATH"

script:
  - phpcs --standard=.phpcs.xml "$TRAVIS_BUILD_DIR"
