language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm
  - nightly

script:
  - find . -type f -name '*.php' -print0 | xargs -0 -I file php -l file > /dev/null

before_deploy:
  # Generate API documentation
  - sh -c "php $TRAVIS_BUILD_DIR/vendor/bin/phpdoc -d $TRAVIS_BUILD_DIR -t $TRAVIS_BUILD_DIR/build/docs/pico-$TRAVIS_TAG"
  # Send documentation to Github Pages
  - sh -c "bash $TRAVIS_BUILD_DIR/build/deploy-phpdoc.sh;"
  # remove req-dev depenedencies
  - composer update --no-dev
  # package Pico
  - tar -czf "pico-release-$TRAVIS_TAG.tar.gz" .htaccess README.md CHANGELOG.md CONTRIBUTING.md composer.json composer.lock LICENSE config content-sample lib plugins themes vendor index.php

deploy:
  provider: releases
  api_key: ${GITHUB_OAUTH_TOKEN}
  file: pico-release-$TRAVIS_TAG.tar.gz
  skip_cleanup: true
  on:
    repo: picocms/Pico
    tags: true
    php: 5.3

sudo: false
